version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=sitemate
      - DB_HOST=db
      - DB_PORT=5433
    depends_on:
      - db
  db:
    image: "postgres:14"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sitemate
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
volumes:
  postgres_data:
